#!/usr/bin/env python3
"""Emit src/v3/learning/contract-act-v1.json from the V1 content pack."""
from __future__ import annotations

import json
from pathlib import Path

SECTIONS = [
    {"slug": "foundations", "title_en": "Foundations", "title_bn": "মৌলিক ধারণা", "minutes": 4, "order": 1},
    {"slug": "offer-invitation-revocation", "title_en": "Offer, Invitation & Revocation", "title_bn": "প্রস্তাব, আমন্ত্রণ ও প্রত্যাহার", "minutes": 5, "order": 2},
    {"slug": "acceptance", "title_en": "Acceptance", "title_bn": "গ্রহণ", "minutes": 4, "order": 3},
    {"slug": "consideration", "title_en": "Consideration", "title_bn": "প্রতিদান", "minutes": 5, "order": 4},
    {"slug": "capacity", "title_en": "Capacity to Contract", "title_bn": "চুক্তি করার যোগ্যতা", "minutes": 5, "order": 5},
    {"slug": "free-consent", "title_en": "Free Consent", "title_bn": "স্বাধীন সম্মতি", "minutes": 5, "order": 6},
    {"slug": "void-agreements", "title_en": "Void Agreements", "title_bn": "বাতিল চুক্তি", "minutes": 5, "order": 7},
    {"slug": "breach-discharge-remedies", "title_en": "Breach, Discharge & Remedies", "title_bn": "ভঙ্গ, অব্যাহতি ও প্রতিকার", "minutes": 5, "order": 8},
]

# slug, type, visual, label, hook_en, hook_bn, q_en, q_bn, a_en, a_bn, exp_en, exp_bn, key_en, key_bn, section_label, authority
RAW = [
("c01", "foundations", "counterintuitive", "spline", "DID YOU KNOW",
 "Not every agreement is a contract.", "সব সমঝোতাই চুক্তি নয়।",
 "You promise a friend you will meet for tea tomorrow. Is that automatically a legally enforceable contract?",
 "আপনি বন্ধুকে কাল চায়ের জন্য দেখা করার প্রতিশ্রুতি দিলেন। এটা কি স্বয়ংক্রিয়ভাবে আইনে কার্যকর চুক্তি?",
 "NO — not automatically.", "না — স্বয়ংক্রিয়ভাবে নয়।",
 "A contract is an agreement enforceable by law. Section 10 adds the core requirements: free consent, competent parties, lawful consideration, lawful object, and no rule making the agreement void. A social promise may never reach that legal threshold.",
 "চুক্তি হলো আইনে কার্যকর সমঝোতা। ধারা ১০-এ স্বাধীন সম্মতি, যোগ্য পক্ষ, বৈধ প্রতিদান ও উদ্দেশ্য লাগে। সামাজিক প্রতিশ্রুতি সেই মানে নাও পৌঁছাতে পারে।",
 "Not every agreement is a contract — only those enforceable by law.",
 "সব সমঝোতা চুক্তি নয়—আইনে কার্যকর করার মতো হলে তবেই contract.",
 "§§2(h), 10", "statute", None),
("c02", "foundations", "rule_visualizer", "lottie", "DID YOU KNOW",
 "An accepted proposal becomes something new.", "গৃহীত প্রস্তাব নতুন কিছু হয়ে যায়।",
 "Rafi offers to sell a desk to Nila for ৳5,000. Nila accepts. What has the proposal become?",
 "রাফি নিলা-কে ৫,০০০ টাকায় ডেস্ক বিক্রির প্রস্তাব দিল, নিলা গ্রহণ করল। প্রস্তাবটি কী হয়েছে?",
 "A PROMISE.", "একটি প্রতিশ্রুতি (promise)।",
 "When the person receiving a proposal signifies assent, the proposal is accepted; once accepted, it becomes a promise. This is the first transformation students should remember in contract formation.",
 "প্রস্তাব গ্রহণকারী সম্মতি জানালে সেটি accepted হয় এবং promise হয়ে যায়। গঠনের প্রথম রূপান্তর এটি।",
 "An accepted proposal becomes a promise.",
 "প্রস্তাব গ্রহণ করা হলে সেটি promise বা প্রতিশ্রুতিতে পরিণত হয়.",
 "§2(b)", "statute", None),
("c03", "foundations", "myth_buster", "image", "MYTH CHECK",
 "The buyer is not always the “promisor.”", "ক্রেতা সবসময় promisor নন।",
 "Who is the promisor: the person making the proposal, or the person accepting it?",
 "Promisor কে—যিনি প্রস্তাব দেন, নাকি যিনি গ্রহণ করেন?",
 "The proposal-maker.", "যিনি প্রস্তাব দেন।",
 "Under section 2(c), the person making the proposal is called the promisor, and the person accepting it is the promisee. The labels follow the proposal—not whether someone is buyer or seller.",
 "ধারা ২(গ) অনুসারে প্রস্তাবদাতা promisor, গ্রহণকারী promisee। ক্রেতা-বিক্রেতা নয়, প্রস্তাবই লেবেল নির্ধারণ করে।",
 "The proposal-maker is the promisor; the acceptor is the promisee.",
 "যিনি proposal দেন তিনি promisor; যিনি গ্রহণ করেন তিনি promisee.",
 "§2(c)", "statute", None),
("c04", "foundations", "rule_visualizer", "image", "DID YOU KNOW",
 "Many contracts are two promises crossing.", "অনেক চুক্তি দুই প্রতিশ্রুতির আদান-প্রদান।",
 "You promise to pay ৳2,000 and a seller promises to deliver a chair. What kind of promises are these?",
 "আপনি ২,০০০ টাকা দেওয়ার এবং বিক্রেতা চেয়ার দেওয়ার প্রতিশ্রুতি দিলেন। এগুলো কী ধরনের promise?",
 "RECIPROCAL PROMISES.", "পারস্পরিক প্রতিশ্রুতি।",
 "Promises that form the consideration, or part of the consideration, for each other are reciprocal promises. Everyday sales are easy examples: payment and delivery are connected promises moving in opposite directions.",
 "একে অপরের প্রতিদান হয় এমন প্রতিশ্রুতি reciprocal। বেচাকেনায় টাকা ও পণ্য দুই দিকের promise।",
 "Crossing promises that support each other are reciprocal promises.",
 "দুই পক্ষের পরস্পর-নির্ভর প্রতিশ্রুতি reciprocal promises.",
 "§2(f)", "statute", None),
("c05", "foundations", "myth_buster", "image", "MYTH CHECK",
 "Void and voidable do NOT mean the same thing.", "Void আর voidable এক নয়।",
 "One agreement cannot be enforced at all; another can be avoided by one party. Are they legally the same?",
 "একটি চুক্তি একেবারেই অকার্যকর; অন্যটি এক পক্ষ বাতিল করতে পারে। এগুলো কি আইনে এক?",
 "NO.", "না।",
 "A void agreement is not enforceable by law. A voidable contract remains enforceable at the option of one or more parties, but not the other. That difference matters throughout consent and mistake problems.",
 "Void agreement আইনে অকার্যকর। Voidable চুক্তি এক বা একাধিক পক্ষের ইচ্ছায় এড়ানো যায়। সম্মতি ও ভুলের প্রশ্নে পার্থক্য জরুরি।",
 "Void is unenforceable; voidable can be avoided by one side.",
 "Void মানে আইনেই অকার্যকর; voidable মানে নির্দিষ্ট পক্ষ চাইলে বাতিল করতে পারে.",
 "§§2(g), 2(i)", "statute", None),
("c06", "offer-invitation-revocation", "counterintuitive", "image", "DID YOU KNOW",
 "A display can invite an offer without making one.", "প্রদর্শন offer না করে offer আমন্ত্রণ করতে পারে।",
 "A shop displays a laptop with a price. Does the display always mean the shop is legally bound to sell to whoever points at it?",
 "দোকানে ল্যাপটপের দাম লেখা। যে কেউ দেখালেই কি দোকান বাধ্য বিক্রি করতে?",
 "NO — context matters.", "না — প্রসঙ্গ দেখতে হয়।",
 "Contract-law courses distinguish a true proposal from an invitation to treat. A display or advertisement may invite customers to make proposals rather than itself create a binding proposal. The Contract Act does not expressly define invitation to treat.",
 "সত্যিকারের proposal আর invitation to treat আলাদা। ডিসপ্লে গ্রাহককে প্রস্তাব দিতে আমন্ত্রণ জানাতে পারে, নিজে বাধ্যতামূলক proposal নাও হতে পারে। আইনে শব্দটি স্পষ্ট সংজ্ঞায়িত নয়।",
 "A shop display is often an invitation to treat, not a finished offer.",
 "দোকানের display সবসময় offer নয়; অনেক সময় এটি offer করার invitation.",
 "§2(a) framework", "doctrine",
 "Invitation to treat is taught as doctrine. Attach reviewer-approved case authority before treating this card as fully statutory."),
("c07", "offer-invitation-revocation", "scenario", "spline", "TRY THIS",
 "An unseen offer has not finished communicating.", "অদেখা offer-এর communication শেষ হয়নি।",
 "Sami writes an offer at 10 AM but the message reaches Rupa at 2 PM. When is communication of the proposal complete?",
 "সামি সকাল ১০টায় offer লেখে, রূপা দুপুর ২টায় পায়। Communication কখন complete?",
 "When Rupa knows of it.", "যখন রূপা জানতে পারে।",
 "Communication of a proposal is complete when it comes to the knowledge of the person to whom it is made. Writing or sending it is not enough by itself.",
 "Proposal-এর communication তখনই complete যখন যাকে করা হয়েছে তিনি জানতে পারেন। শুধু লেখা বা পাঠানো যথেষ্ট নয়।",
 "A proposal is communicated when the other person knows of it.",
 "Proposal অন্য পক্ষের জানা হলে তার communication complete হয়.",
 "§4", "statute", None),
("c08", "offer-invitation-revocation", "rule_visualizer", "lottie", "DID YOU KNOW",
 "An offer is not untouchable once sent.", "পাঠানোর পরই offer অপরিবর্তনীয় নয়।",
 "Can the proposer withdraw a proposal before the acceptance becomes complete against the proposer?",
 "Acceptor-এর acceptance proposer-এর বিরুদ্ধে complete হওয়ার আগে কি প্রস্তাব তুলে নেওয়া যায়?",
 "YES.", "হ্যাঁ।",
 "Section 5 allows a proposal to be revoked any time before communication of acceptance is complete against the proposer—but not afterwards. Timing is therefore critical.",
 "ধারা ৫: acceptance proposer-এর বিরুদ্ধে complete হওয়ার আগে proposal revoke করা যায়, পরে নয়। সময়ই মূল।",
 "A proposal can be revoked until acceptance is complete against the proposer.",
 "Acceptance proposer-এর বিরুদ্ধে complete হওয়ার আগে proposal প্রত্যাহার করা যায়.",
 "§5", "statute", None),
("c09", "offer-invitation-revocation", "scenario", "image", "TRY THIS",
 "Changing your mind privately changes nothing.", "মনে মনে বদলালে কিছু হয় না।",
 "You decide at noon to cancel yesterday’s offer but tell nobody. Has the revocation been communicated?",
 "দুপুরে গতকালের offer বাতিল ঠিক করলেন কিন্তু কাউকে বললেন না। Revocation communicated হয়েছে?",
 "NO.", "না।",
 "A proposal is revoked by communicating notice of revocation to the other party. A private decision inside the proposer’s mind is not enough.",
 "Revocation অন্য পক্ষকে জানাতে হয়। শুধু মনের সিদ্ধান্ত যথেষ্ট নয়।",
 "Revocation must be communicated to the other party.",
 "মনে মনে offer বাতিল করলেই হবে না—revocation অন্য পক্ষকে জানাতে হবে.",
 "§6(1)", "statute", None),
("c10", "offer-invitation-revocation", "counterintuitive", "lottie", "DID YOU KNOW",
 "Some offers expire without anyone saying “cancel.”", "কেউ না বললেও কিছু offer মেয়াদ শেষে মরে।",
 "An offer says “accept within 48 hours.” The recipient accepts five days later. Did the original offer survive?",
 "Offer বলে ৪৮ ঘণ্টায় গ্রহণ করুন। পাঁচ দিন পর গ্রহণ করলে কি আসল offer বেঁচে থাকে?",
 "NO — it lapsed.", "না — lapse হয়েছে।",
 "A proposal is revoked by lapse of the time prescribed for acceptance. If no time is prescribed, it can lapse after a reasonable time without communication of acceptance.",
 "নির্ধারিত সময় পার হলে proposal revoke/lapse হয়। সময় না থাকলে যুক্তিসঙ্গত সময় পরেও lapse হতে পারে।",
 "An offer can lapse when the time for acceptance runs out.",
 "নির্ধারিত সময় পার হলে offer নিজেই lapse করতে পারে.",
 "§6(2)", "statute", None),
("c11", "offer-invitation-revocation", "scenario", "image", "TRY THIS",
 "Ignore a required condition and the offer may disappear.", "প্রয়োজনীয় শর্ত না মানলে offer হারিয়ে যেতে পারে।",
 "An offer requires a ৳1,000 booking deposit before acceptance. The recipient never pays it. Can the failure affect the proposal?",
 "Acceptance-এর আগে ১,০০০ টাকা বুকিং লাগে, গ্রহণকারী দেয়নি। এতে proposal ক্ষতিগ্রস্ত হতে পারে?",
 "YES.", "হ্যাঁ।",
 "A proposal may be revoked by the acceptor’s failure to fulfil a condition precedent to acceptance. The condition must be part of the acceptance setup, not invented later.",
 "Acceptance-এর পূর্বশর্ত না মানলে proposal revoke হতে পারে। শর্ত পরে বানানো চলবে না।",
 "Failure of a condition precedent can revoke a proposal.",
 "Acceptance-এর আগে প্রয়োজনীয় condition না মানলে proposal revoke হতে পারে.",
 "§6(3)", "statute", None),
("c12", "offer-invitation-revocation", "edge_case", "image", "DID YOU KNOW",
 "Death matters only when the acceptor knows in time.", "মৃত্যু তখনই গুরুত্বপূর্ণ যখন acceptor সময়মতো জানে।",
 "The proposer dies before acceptance, but the acceptor has no knowledge of the death. Does section 6 treat knowledge as relevant?",
 "Acceptance-এর আগে proposer মারা গেলেন, acceptor জানেন না। ধারা ৬-এ জানা কি প্রাসঙ্গিক?",
 "YES.", "হ্যাঁ।",
 "Section 6 provides for revocation by death or insanity of the proposer if the fact comes to the knowledge of the acceptor before acceptance. The knowledge element is important.",
 "Proposer-এর মৃত্যু বা উন্মাদনা acceptance-এর আগে acceptor জানলে revocation ঘটতে পারে। জানাটাই মূল।",
 "Death or insanity revokes only if the acceptor knows before accepting.",
 "Proposer-এর মৃত্যু বা insanity acceptance-এর আগে acceptor-এর জানা গুরুত্বপূর্ণ.",
 "§6(4)", "statute", None),
("c13", "acceptance", "counterintuitive", "spline", "DID YOU KNOW",
 "“Yes, but…” may not be acceptance.", "‘হ্যাঁ, তবে…’ গ্রহণ নাও হতে পারে।",
 "An offer is ৳20,000. The reply says, “I accept if you reduce it to ৳17,000.” Is that absolute acceptance?",
 "Offer ২০,০০০ টাকা। জবাব: ‘১৭,০০০ করলে গ্রহণ করি।’ এটা কি নিঃশর্ত acceptance?",
 "NO.", "না।",
 "To convert a proposal into a promise, acceptance must be absolute and unqualified. A reply that changes the deal is not the clean acceptance section 7 requires.",
 "Promise হতে হলে acceptance নিঃশর্ত হতে হয়। শর্ত বদলালে ধারা ৭-এর clean acceptance হয় না।",
 "Acceptance must be absolute and unqualified.",
 "Acceptance শর্তহীন ও সম্পূর্ণ হতে হবে; নতুন শর্ত দিলে সেটি clean acceptance নয়.",
 "§7(1)", "statute", None),
("c14", "acceptance", "scenario", "image", "TRY THIS",
 "How you accept can matter.", "কীভাবে গ্রহণ করবেন তা গুরুত্বপূর্ণ হতে পারে।",
 "The offer asks for acceptance by signed email, but you send a voice note. Can the prescribed manner become relevant?",
 "Offer চায় স্বাক্ষরিত ইমেইল, আপনি ভয়েস নোট পাঠালেন। নির্ধারিত পদ্ধতি কি প্রাসঙ্গিক?",
 "YES.", "হ্যাঁ।",
 "Section 7 says acceptance should be in the prescribed manner when one is set. If acceptance uses another method, the proposer may insist on the prescribed method within a reasonable time; otherwise the proposer may be treated as accepting the alternative manner.",
 "নির্ধারিত পদ্ধতি থাকলে সেভাবে গ্রহণ করা উচিত। অন্যভাবে করলে proposer যুক্তিসঙ্গত সময়ে জোর দিতে পারেন।",
 "A prescribed manner of acceptance can legally matter.",
 "Offer-এ acceptance-এর নির্দিষ্ট পদ্ধতি থাকলে সেটি গুরুত্বপূর্ণ.",
 "§7(2)", "statute", None),
("c15", "acceptance", "rule_visualizer", "lottie", "DID YOU KNOW",
 "You can accept without saying “I accept.”", "‘গ্রহণ করলাম’ না বলেও গ্রহণ হতে পারে।",
 "A reward proposal asks someone to complete a specified task. Can performing the condition amount to acceptance?",
 "পুরস্কারের proposal নির্দিষ্ট কাজ চায়। কাজটি করা কি acceptance হতে পারে?",
 "YES.", "হ্যাঁ।",
 "Performance of the conditions of a proposal, or acceptance of consideration offered with it for a reciprocal promise, can amount to acceptance. Contract formation can therefore happen through conduct.",
 "Proposal-এর শর্ত পালন বা প্রতিদান গ্রহণ acceptance হতে পারে। আচরণেও চুক্তি গঠিত হয়।",
 "Doing the requested act can be acceptance.",
 "কাজ করে condition পূরণ করাও acceptance হতে পারে.",
 "§8", "statute", None),
("c16", "acceptance", "myth_buster", "image", "MYTH CHECK",
 "A contract does not always need spoken words.", "চুক্তিতে সবসময় কথা লাগে না।",
 "You board a service, pay the stated fare and receive the service without negotiating aloud. Can promises be implied?",
 "সেবায় উঠে নির্ধারিত ভাড়া দিলেন, কথা বলেননি। Implied promise কি হতে পারে?",
 "YES.", "হ্যাঁ।",
 "Section 9 distinguishes express promises made in words from implied promises made otherwise than in words. Conduct can communicate contractual intention.",
 "ধারা ৯: কথায় express, কথা ছাড়া implied promise। আচরণেও contractual intention প্রকাশ পায়।",
 "Promises can be implied from conduct, not only words.",
 "কথা বা লেখা ছাড়াও আচরণ থেকে implied promise তৈরি হতে পারে.",
 "§9", "statute", None),
("c17", "acceptance", "edge_case", "image", "DID YOU KNOW",
 "One acceptance can be “complete” at two different times.", "এক acceptance দুই সময়ে complete হতে পারে।",
 "B posts an acceptance to A. Is communication complete against A and B at exactly the same moment?",
 "B ডাকে acceptance পাঠাল A-কে। A ও B-এর বিরুদ্ধে কি একই মুহূর্তে complete?",
 "NO.", "না।",
 "Under section 4, acceptance is complete against the proposer when it is put into transmission beyond the acceptor’s power. Against the acceptor, it is complete when it comes to the proposer’s knowledge.",
 "ধারা ৪: proposer-এর বিরুদ্ধে পাঠানোর পর complete; acceptor-এর বিরুদ্ধে proposer জানলে complete।",
 "Postal acceptance completes at different moments for each party.",
 "Posted acceptance proposer ও acceptor-এর বিরুদ্ধে একই সময়ে complete নাও হতে পারে.",
 "§4", "statute", None),
("c18", "consideration", "counterintuitive", "spline", "DID YOU KNOW",
 "Consideration need not come only from the promisee.", "Consideration শুধু promisee থেকে আসতে হয় না।",
 "Can “the promisee or any other person” provide the act, abstinence or promise that counts as consideration?",
 "Promisee বা অন্য কেউ কি consideration দিতে পারেন?",
 "YES.", "হ্যাঁ।",
 "Section 2(d) expressly says consideration may move from the promisee or any other person, so long as it is at the desire of the promisor and fits the statutory definition. Bangladesh law differs from traditional English law here.",
 "ধারা ২(ঘ): consideration promisee বা অন্য ব্যক্তি থেকে আসতে পারে, promisor-এর ইচ্ছায়। এখানে ইংরেজ আইন থেকে বাংলাদেশ আলাদা।",
 "Consideration may move from the promisee or any other person.",
 "Consideration শুধু promisee থেকেই আসতে হবে—এমন নয়.",
 "§2(d)", "statute", None),
("c19", "consideration", "rule_visualizer", "image", "DID YOU KNOW",
 "Consideration is not trapped in the present.", "Consideration শুধু বর্তমানে আটকে নেই।",
 "The Act says a person “has done,” “does,” or “promises to do” something. What does that suggest?",
 "আইন বলে কেউ ‘করেছে’, ‘করে’, বা ‘করবে’। এর মানে কী?",
 "Timing can vary.", "সময় ভিন্ন হতে পারে।",
 "The language of section 2(d) covers an act or abstinence already done, being done, or promised for the future, provided the statutory requirements are met.",
 "ধারা ২(ঘ) অতীত, বর্তমান ও ভবিষ্যৎ কাজ বা বিরতিকে ঢাকে, যদি সংজ্ঞা মেলে।",
 "Consideration can relate to past, present or future acts.",
 "Consideration অতীত, বর্তমান বা ভবিষ্যৎ কাজের সঙ্গে যুক্ত হতে পারে.",
 "§2(d)", "statute", None),
("c20", "consideration", "myth_buster", "image", "MYTH CHECK",
 "A bare promise is usually not enough.", "শুধু প্রতিশ্রুতি সাধারণত যথেষ্ট নয়।",
 "A promises to gift B ৳10,000 later, with no consideration and no applicable exception. Is the agreement generally valid as a contract?",
 "A পরে B-কে ১০,০০০ উপহারের প্রতিশ্রুতি দিল, consideration নেই, exceptionও নেই। এটা কি সাধারণত বৈধ চুক্তি?",
 "NO — generally void.", "না — সাধারণত void।",
 "Section 25 starts with the rule that an agreement without consideration is void, then creates specific exceptions. Students should learn both the default rule and the exceptions.",
 "ধারা ২৫: consideration ছাড়া agreement সাধারণত void, তারপর নির্দিষ্ট ব্যতিক্রম। দুটোই শিখতে হয়।",
 "No consideration usually makes the agreement void, subject to section 25 exceptions.",
 "সাধারণ নিয়মে consideration ছাড়া agreement void—তবে section 25-এ exception আছে.",
 "§25", "statute", None),
("c21", "consideration", "counterintuitive", "lottie", "DID YOU KNOW",
 "Love can support a contract—but not by itself.", "ভালোবাসা চুক্তি টানতে পারে—একা নয়।",
 "Can natural love and affection between near relatives support an agreement without ordinary consideration?",
 "নিকট আত্মীয়ের স্বাভাবিক স্নেহ কি সাধারণ consideration ছাড়া agreement টানতে পারে?",
 "YES — with formalities.", "হ্যাঁ — আনুষ্ঠানিকতায়।",
 "Section 25(1) recognizes an exception where the agreement is in writing, registered, and made on account of natural love and affection between parties standing in a near relation. Do not teach this as love alone is consideration.",
 "ধারা ২৫(১): লিখিত, রেজিস্টার্ড, নিকট সম্পর্কে স্বাভাবিক স্নেহ। শুধু ভালোবাসাই consideration নয়।",
 "Love and affection needs writing and registration under section 25(1).",
 "নিকট আত্মীয়ের love and affection exception-এ writing ও registration দুটোই জরুরি.",
 "§25(1)", "statute", None),
("c22", "consideration", "scenario", "image", "TRY THIS",
 "A past voluntary act can sometimes support a later promise.", "আগের স্বেচ্ছায় করা কাজ পরে প্রতিশ্রুতি টানতে পারে।",
 "You voluntarily return someone’s lost wallet. Afterwards the owner promises you ৳1,000. Can section 25 recognize this?",
 "হারানো ওয়ালেট ফিরিয়ে দিলেন। পরে মালিক ১,০০০ দেওয়ার প্রতিশ্রুতি দিল। ধারা ২৫ কি চিনতে পারে?",
 "YES — potentially.", "হ্যাঁ — সম্ভাব্য।",
 "Section 25(2) covers a promise to compensate, wholly or partly, a person who has already voluntarily done something for the promisor, or something the promisor was legally compellable to do.",
 "ধারা ২৫(২): promisor-এর জন্য আগে স্বেচ্ছায় করা কাজের আংশিক বা পূর্ণ ক্ষতিপূরণের promise।",
 "A later promise can reward a past voluntary act.",
 "Promisor-এর জন্য আগে স্বেচ্ছায় করা কাজের compensation-এর promise বৈধ হতে পারে.",
 "§25(2)", "statute", None),
("c23", "consideration", "edge_case", "image", "DID YOU KNOW",
 "An old unenforceable debt can still produce a new contract.", "পুরনো অকার্যকর ঋণ নতুন চুক্তি জন্মাতে পারে।",
 "A debt is time-barred. The debtor signs a written promise to pay part of it. Can section 25 treat that promise as a contract?",
 "ঋণ সময়বাধিত। দেনাদার অংশ পরিশোধের লিখিত প্রতিশ্রুতি দিলেন। ধারা ২৫ কি একে চুক্তি মানবে?",
 "YES.", "হ্যাঁ।",
 "Section 25(3) recognizes a written and signed promise to pay wholly or partly a debt that could have been enforced but for limitation law. The writing/signature requirements matter.",
 "ধারা ২৫(৩): সময়বাধিত ঋণের লিখিত স্বাক্ষরিত পরিশোধের প্রতিশ্রুতি নতুন করে enforceable হতে পারে।",
 "A signed written promise can revive a time-barred debt.",
 "Time-barred debt-এর লিখিত ও signed repayment promise নতুনভাবে enforceable হতে পারে.",
 "§25(3)", "statute", None),
("c24", "consideration", "counterintuitive", "image", "DID YOU KNOW",
 "Bad bargain does not automatically mean no contract.", "খারাপ দরদাম মানেই চুক্তি নেই নয়।",
 "A freely agrees to sell an item worth ৳10,000 for ৳1,000. Is the agreement void merely because the consideration is inadequate?",
 "A স্বাধীনভাবে ১০,০০০ টাকার জিনিস ১,০০০-এ বিক্রি করতে রাজি। শুধু অপর্যাপ্ত consideration-এ কি void?",
 "NO — not merely for that.", "না — শুধু সেই কারণে নয়।",
 "Section 25 says a freely made agreement is not void merely because consideration is inadequate. But serious inadequacy may be relevant when a court asks whether consent was truly free.",
 "ধারা ২৫: স্বাধীন চুক্তি শুধু অপর্যাপ্ত consideration-এ void নয়। তবে সম্মতি সত্যি স্বাধীন কি না যাচাইয়ে তা দেখা যায়।",
 "Inadequate consideration does not automatically void a free agreement.",
 "Consideration কম হলেই contract void নয়; তবে free consent যাচাইয়ে তা গুরুত্বপূর্ণ হতে পারে.",
 "§25, Explanation 2", "statute", None),
("c25", "capacity", "edge_case", "spline", "DID YOU KNOW",
 "“Adult at 18” has a statutory exception.", "১৮-এ প্রাপ্তবয়স্ক—এর আইনি ব্যতিক্রম আছে।",
 "For people domiciled in Bangladesh, is 18 always the only majority age mentioned by the Majority Act?",
 "বাংলাদেশে ডমিসাইল ব্যক্তির জন্য Majority Act-এ কি শুধু ১৮-ই আছে?",
 "NO.", "না।",
 "The general rule is majority at 18. But section 3 of the Majority Act provides a 21-year rule in specified situations involving a court-appointed guardian of person/property or Court of Wards superintendence. Contract Act section 11 ties capacity to the applicable age of majority.",
 "সাধারণত ১৮। নির্দিষ্ট অভিভাবক/Court of Wards ক্ষেত্রে Majority Act ধারা ৩-এ ২১ হতে পারে। চুক্তি আইনের ধারা ১১ সেই বয়সের সঙ্গে যুক্ত।",
 "Majority is usually 18, sometimes 21 under the Majority Act.",
 "সাধারণভাবে majority ১৮; তবে Majority Act-এর নির্দিষ্ট guardian/Court of Wards ক্ষেত্রে ২১ হতে পারে.",
 "§11; Majority Act 1875 §3", "statute", None),
("c26", "capacity", "myth_buster", "image", "MYTH CHECK",
 "Being 18+ is not the whole capacity test.", "১৮+ হওয়াই পুরো capacity নয়।",
 "If someone has reached majority, are they automatically competent to contract in every case?",
 "Majority পেলেই কি সব ক্ষেত্রে চুক্তিযোগ্য?",
 "NO.", "না।",
 "Section 11 requires three things: age of majority under the applicable law, sound mind, and no legal disqualification from contracting. Age is only one part of the capacity test.",
 "ধারা ১১: প্রাপ্তবয়স্কতা, সুস্থ মন, এবং অন্য আইনে নিষেধ না থাকা। বয়স শুধু এক অংশ।",
 "Capacity needs majority, sound mind, and no legal disqualification.",
 "Capacity-এর জন্য majority, sound mind এবং কোনো legal disqualification না থাকা দরকার.",
 "§11", "statute", None),
("c27", "capacity", "counterintuitive", "lottie", "DID YOU KNOW",
 "Capacity can change from one hour to another.", "Capacity ঘণ্টায় ঘণ্টায় বদলাতে পারে।",
 "A person is usually of unsound mind but has a lucid interval. Can they contract during that interval?",
 "সাধারণত অসুস্থ মস্তিষ্ক, কিন্তু স্বচ্ছ মুহূর্ত আছে। সেই সময়ে কি চুক্তি করা যায়?",
 "YES — if capable then.", "হ্যাঁ — তখন সক্ষম হলে।",
 "Section 12 focuses on the person’s ability at the time of the contract: can they understand it and form a rational judgment about its effect on their interests? A usually unsound person may contract during a sound interval.",
 "ধারা ১২ চুক্তির সময়ের সক্ষমতা দেখে: বোঝা ও স্বার্থের প্রভাব বিচার। স্বচ্ছ মুহূর্তে চুক্তি হতে পারে।",
 "Sound mind is tested at the time of contracting.",
 "Contract-এর সময় বোঝার ও rational judgment করার ক্ষমতাই মূল test.",
 "§12", "statute", None),
("c28", "capacity", "scenario", "image", "TRY THIS",
 "Being drunk can become a contract-capacity issue.", "মাতাল অবস্থা capacity-র সমস্যা হতে পারে।",
 "A person is so drunk that they cannot understand the terms or judge the effect on their interests. Are they competent at that moment?",
 "এত মাতাল যে শর্ত বোঝে না বা স্বার্থ বিচার করতে পারে না। সেই মুহূর্তে কি যোগ্য?",
 "NO.", "না।",
 "Section 12 illustrates that a normally sane person who is so drunk—or delirious from fever—that they cannot understand the contract or form a rational judgment cannot contract while that condition lasts.",
 "ধারা ১২: সাধারণত সুস্থ ব্যক্তিও এত মাতাল বা জ্বরে বিভ্রান্ত যে বুঝতে পারে না, সেই অবস্থায় চুক্তি করতে পারে না।",
 "Severe intoxication can remove competence for that moment.",
 "এত intoxicated হলে যে terms বোঝা যায় না, সেই সময়ে contractual capacity থাকে না.",
 "§12", "statute", None),
("c29", "capacity", "rule_visualizer", "image", "DID YOU KNOW",
 "Age and sanity can still be insufficient.", "বয়স ও সুস্থ মনও অপর্যাপ্ত হতে পারে।",
 "Can a person be of majority age and sound mind yet still lack competence because another law disqualifies them?",
 "প্রাপ্তবয়স্ক ও সুস্থ মন নিয়েও কি অন্য আইন চুক্তি নিষেধ করতে পারে?",
 "YES.", "হ্যাঁ।",
 "Section 11 expressly includes a third requirement: the person must not be disqualified from contracting by any law to which they are subject.",
 "ধারা ১১-এ তৃতীয় শর্ত: যে আইনের অধীন, সে আইন চুক্তি নিষেধ করলে যোগ্যতা থাকে না।",
 "Another law can disqualify a person from contracting.",
 "অন্য কোনো আইন contract করতে নিষেধ করলে age ও sound mind থাকলেও capacity নাও থাকতে পারে.",
 "§11", "statute", None),
("c30", "capacity", "counterintuitive", "image", "DID YOU KNOW",
 "Necessaries can be reimbursed from property.", "প্রয়োজনীয় জিনিসের খরচ সম্পত্তি থেকে ফেরত আসতে পারে।",
 "A person incapable of contracting receives necessaries suited to their condition in life. From where can the supplier seek reimbursement under section 68?",
 "অযোগ্য ব্যক্তি তার জীবনমান অনুযায়ী necessaries পেল। ধারা ৬৮-এ সরবরাহকারী কোথা থেকে টাকা চাইবে?",
 "From that person’s property.", "সেই ব্যক্তির সম্পত্তি থেকে।",
 "Section 68 creates a reimbursement rule for necessaries supplied to a person incapable of contracting, or someone they are legally bound to support. The statutory claim is against the incapable person’s property.",
 "ধারা ৬৮: অযোগ্য ব্যক্তি বা তার ভরণপোষণে বাধ্য ব্যক্তিকে necessaries দিলে সম্পত্তি থেকে reimbursement।",
 "Necessaries are reimbursed from property, not ordinary personal liability.",
 "Incapable person-কে necessaries দিলে reimbursement তার property থেকে পাওয়া যেতে পারে.",
 "§68", "statute", None),
("c31", "free-consent", "rule_visualizer", "spline", "DID YOU KNOW",
 "Saying “yes” does not always mean free consent.", "‘হ্যাঁ’ বলাই সবসময় স্বাধীন সম্মতি নয়।",
 "Which five legal problems can prevent consent from being “free” under the Contract Act?",
 "চুক্তি আইনে কোন পাঁচ সমস্যা সম্মতিকে অ-স্বাধীন করতে পারে?",
 "Five listed causes.", "আইনে তালিকাভুক্ত পাঁচ কারণ।",
 "Section 14 says consent is free when it is not caused by coercion, undue influence, fraud, misrepresentation, or mistake subject to sections 20–22. The issue is whether consent would have been given but for the improper cause.",
 "ধারা ১৪: coercion, undue influence, fraud, misrepresentation, বা ধারা ২০–২২-এর mistake না থাকলে সম্মতি স্বাধীন।",
 "Free consent is missing if one of five listed causes induced the yes.",
 "Coercion, undue influence, fraud, misrepresentation বা relevant mistake থাকলে consent free নাও হতে পারে.",
 "§14", "statute", None),
("c32", "free-consent", "counterintuitive", "lottie", "DID YOU KNOW",
 "Coercion can target property too.", "Coercion সম্পত্তিকেও লক্ষ্য করতে পারে।",
 "Someone unlawfully detains your property to force you into an agreement. Can that fit statutory coercion?",
 "কেউ অবৈধভাবে আপনার সম্পত্তি আটকে চুক্তি করাল। এটা কি আইনি coercion?",
 "YES.", "হ্যাঁ।",
 "Section 15 includes committing or threatening an act forbidden by the Penal Code and unlawfully detaining or threatening to detain property, when done to cause someone to enter an agreement.",
 "ধারা ১৫: দণ্ডবিধিতে নিষিদ্ধ কাজ/হুমকি এবং সম্পত্তি অবৈধ আটক—চুক্তি করাতে ব্যবহার হলে coercion।",
 "Unlawful detention of property can be coercion.",
 "শুধু শারীরিক threat নয়—property unlawfully আটকিয়েও contract করালে coercion হতে পারে.",
 "§15", "statute", None),
("c33", "free-consent", "scenario", "image", "TRY THIS",
 "Trust can become legal pressure.", "আস্থা আইনি চাপ হয়ে যেতে পারে।",
 "A person who can dominate another’s will uses that position to obtain an unfair advantage. What issue should you spot?",
 "যিনি অন্যের ইচ্ছা নিয়ন্ত্রণ করতে পারেন, সেই অবস্থান অন্যায্য সুবিধায় ব্যবহার করলেন। কী দেখবেন?",
 "UNDUE INFLUENCE.", "অযাচিত প্রভাব।",
 "Section 16 focuses on a relationship where one party is in a position to dominate the will of another and uses that position to obtain an unfair advantage.",
 "ধারা ১৬: এক পক্ষ অন্যের ইচ্ছা নিয়ন্ত্রণের অবস্থানে থেকে অন্যায্য সুবিধা নিলে undue influence।",
 "Dominating someone’s will for unfair advantage is undue influence.",
 "কারও will dominate করে unfair advantage নিলে undue influence হতে পারে.",
 "§16", "statute", None),
("c34", "free-consent", "counterintuitive", "image", "DID YOU KNOW",
 "A fake future promise can be fraud.", "পালন করার ইচ্ছাহীন প্রতিশ্রুতি fraud হতে পারে।",
 "At the moment of promising, a person already has no intention of performing and uses the promise to induce the contract. Can that be fraud?",
 "প্রতিশ্রুতির সময়ই পালনের ইচ্ছা নেই, চুক্তি করাতে ব্যবহার করল। এটা কি fraud?",
 "YES.", "হ্যাঁ।",
 "Section 17 includes a promise made without any intention of performing it as one form of fraud, when committed with intent to deceive or induce the other party into the contract.",
 "ধারা ১৭(৩): পালনের ইচ্ছা ছাড়া প্রতিশ্রুতি, প্রতারণা বা চুক্তি করানোর উদ্দেশ্যে হলে fraud।",
 "A promise never intended to be kept can be fraud.",
 "শুরু থেকেই পালন করার intention না থাকা promise fraud-এর অংশ হতে পারে.",
 "§17(3)", "statute", None),
("c35", "free-consent", "myth_buster", "lottie", "MYTH CHECK",
 "Silence is usually NOT fraud.", "নীরবতা সাধারণত fraud নয়।",
 "A seller knows a fact that could affect a buyer. Is silence automatically fraud every time?",
 "বিক্রেতা ক্রেতাকে প্রভাবিত করতে পারে এমন তথ্য জানে। নীরবতা কি সবসময় fraud?",
 "NO.", "না।",
 "Section 17 says mere silence about facts likely to affect willingness to contract is not fraud. Exceptions arise where there is a duty to speak or silence is equivalent to speech.",
 "ধারা ১৭: নিছক নীরবতা fraud নয়। Duty to speak বা নীরবতাই কথা হলে ব্যতিক্রম।",
 "Mere silence is not fraud unless a duty to speak arises.",
 "Mere silence সাধারণত fraud নয়; duty to speak বা silence-as-speech হলে exception হতে পারে.",
 "§17, Explanation", "statute", None),
("c36", "free-consent", "counterintuitive", "image", "DID YOU KNOW",
 "You can misrepresent without trying to deceive.", "প্রতারিত করতে না চেয়েও misrepresentation হতে পারে।",
 "A person states something untrue believing it to be true, but without adequate basis, and it misleads the other party. Could this be misrepresentation?",
 "মিথ্যা কথা সত্য ভেবে বলল, পর্যাপ্ত ভিত্তি নেই, অন্য পক্ষ বিভ্রান্ত। এটা কি misrepresentation হতে পারে?",
 "YES.", "হ্যাঁ।",
 "Section 18 includes positive assertions not warranted by the maker’s information even when the maker believes them true, along with other innocent misleading conduct.",
 "ধারা ১৮: নিজের তথ্যে সমর্থিত নয় এমন দাবি, বিশ্বাস থাকলেও, misrepresentation হতে পারে।",
 "An honest but unwarranted false statement can be misrepresentation.",
 "ইচ্ছাকৃত deception না থাকলেও ভুল assertion misrepresentation হতে পারে.",
 "§18", "statute", None),
("c37", "free-consent", "scenario", "image", "TRY THIS",
 "A shared mistake can erase the agreement.", "দুই পক্ষের একই ভুল চুক্তি মুছে দিতে পারে।",
 "Both parties contract for a specific item, unaware it had already been destroyed. What can happen if the fact was essential?",
 "দুই পক্ষ নির্দিষ্ট জিনিসের চুক্তি করল, জানে না সেটি আগেই নষ্ট। অপরিহার্য তথ্য হলে কী হতে পারে?",
 "The agreement is void.", "Agreement void।",
 "Section 20 makes an agreement void where both parties are under a mistake about a fact essential to the agreement. Section 22 says one party’s factual mistake alone does not merely by itself make the contract voidable.",
 "ধারা ২০: অপরিহার্য তথ্যে দুই পক্ষের ভুল হলে void। ধারা ২২: এক পক্ষের ভুল একাই voidable করে না।",
 "A shared essential-fact mistake can void the agreement.",
 "Essential fact নিয়ে দুই পক্ষই ভুল হলে agreement void হতে পারে; এক পক্ষের mistake alone যথেষ্ট নয়.",
 "§§20, 22", "statute", None),
("c38", "void-agreements", "scenario", "image", "TRY THIS",
 "A perfectly clear deal can still be void.", "পরিষ্কার চুক্তিও void হতে পারে।",
 "Two competent adults freely agree on clear terms, but the object of the agreement is forbidden by law. Is clarity enough to save it?",
 "দুই যোগ্য প্রাপ্তবয়স্ক পরিষ্কার শর্তে রাজি, কিন্তু উদ্দেশ্য আইননিষিদ্ধ। পরিষ্কার ভাষা কি বাঁচায়?",
 "NO.", "না।",
 "Section 23 requires lawful consideration and lawful object. If the object or consideration is forbidden by law, defeats law, is fraudulent, injures person/property, or is immoral or opposed to public policy, the agreement is void.",
 "ধারা ২৩: প্রতিদান ও উদ্দেশ্য বৈধ হতে হয়। নিষিদ্ধ, প্রতারণামূলক, ক্ষতিকর বা নীতিবিরুদ্ধ হলে void।",
 "Unlawful object or consideration makes the agreement void.",
 "Terms clear হলেও object বা consideration unlawful হলে agreement void.",
 "§23", "statute", None),
("c39", "void-agreements", "counterintuitive", "image", "DID YOU KNOW",
 "One unlawful part can sink a combined agreement.", "এক অবৈধ অংশ পুরো চুক্তি ডোবাতে পারে।",
 "A single consideration supports several connected objects, and part of that consideration or an object is unlawful. Can the agreement be void?",
 "এক প্রতিদান কয়েকটি যুক্ত উদ্দেশ্য টানে, তার অংশ অবৈধ। পুরো agreement কি void হতে পারে?",
 "YES.", "হ্যাঁ।",
 "Section 24 provides that if part of a single consideration for one or more objects—or part of one of several considerations for a single object—is unlawful, the agreement is void.",
 "ধারা ২৪: এক combined consideration/object-এর অংশ অবৈধ হলে পুরো agreement void হতে পারে।",
 "One unlawful piece can void a single combined bargain.",
 "একটি combined agreement-এর consideration/object-এর অংশ unlawful হলেও পুরো agreement void হতে পারে.",
 "§24", "statute", None),
("c40", "void-agreements", "myth_buster", "image", "MYTH CHECK",
 "A contract cannot freely ban your lawful trade forever.", "চুক্তি ইচ্ছেমতো বৈধ পেশা চিরকাল বন্ধ করতে পারে না।",
 "An agreement restrains someone from exercising a lawful profession, trade or business. What is the general statutory rule?",
 "কেউ বৈধ পেশা/ব্যবসা করতে পারবে না—এমন চুক্তির সাধারণ নিয়ম কী?",
 "Void to that extent.", "সেই অংশে void।",
 "Section 27 makes agreements restraining lawful profession, trade or business void to that extent, subject to the statutory goodwill-sale exception and its reasonableness/local-limit conditions.",
 "ধারা ২৭: বৈধ পেশা/ব্যবসা নিয়ন্ত্রণ সেই অংশে void। goodwill বিক্রির ব্যতিক্রম শর্তসাপেক্ষ।",
 "Restraint of trade is generally void to that extent.",
 "Lawful profession/trade/business restrain করা agreement সাধারণভাবে ওই অংশে void.",
 "§27", "statute", None),
("c41", "void-agreements", "scenario", "image", "TRY THIS",
 "A contract cannot simply erase the courthouse.", "চুক্তি আদালত মুছে দিতে পারে না।",
 "A clause absolutely prevents a party from enforcing contractual rights through ordinary tribunals. Is that automatically safe?",
 "সাধারণ আদালতে অধিকার প্রয়োগ একেবারে বন্ধ করে দেওয়া clause কি নিরাপদ?",
 "NO.", "না।",
 "Section 28 makes such absolute restrictions void to that extent and also addresses clauses limiting the time for enforcing rights. Specified arbitration agreements are preserved.",
 "ধারা ২৮: অধিকার প্রয়োগ একেবারে বন্ধ করা সেই অংশে void। নির্দিষ্ট সালিশি চুক্তি বাঁচে।",
 "You generally cannot contract away ordinary legal enforcement absolutely.",
 "Court-এ contractual right enforce করা একেবারে বন্ধ করে দেওয়া clause সাধারণভাবে void; arbitration exception আছে.",
 "§28", "statute", None),
("c42", "void-agreements", "rule_visualizer", "lottie", "DID YOU KNOW",
 "Too vague can mean no contract.", "অস্পষ্ট মানে চুক্তি নাও থাকতে পারে।",
 "A agrees to sell B “100 tons of oil,” with nothing showing what kind of oil is intended. What issue appears?",
 "A B-কে ‘১০০ টন তেল’ বেচতে রাজি, কোন তেল বোঝা যায় না। সমস্যা কী?",
 "UNCERTAINTY.", "অনিশ্চয়তা।",
 "Section 29 says agreements whose meaning is not certain, or capable of being made certain, are void. Context can sometimes make apparently broad wording certain.",
 "ধারা ২৯: অর্থ নিশ্চিত বা নিশ্চিত করা সম্ভব না হলে void। প্রসঙ্গ কখনো অর্থ স্পষ্ট করে।",
 "Uncertain meaning can make an agreement void.",
 "Agreement-এর meaning certain বা certain করা সম্ভব না হলে তা void.",
 "§29", "statute", None),
("c43", "void-agreements", "counterintuitive", "image", "DID YOU KNOW",
 "Winning the bet does not make the wager enforceable.", "বাজি জিতলেই তা আদালতে টানা যায় না।",
 "Two people make an agreement purely by way of wager on an uncertain event. What is the Contract Act’s rule?",
 "দুইজন অনিশ্চিত ঘটনায় নিছক বাজির চুক্তি করল। আইনের নিয়ম কী?",
 "The agreement is void.", "Agreement void।",
 "Section 30 says agreements by way of wager are void and bars suits for recovering something alleged to be won on a wager or entrusted to abide by the result.",
 "ধারা ৩০: wagering agreement void; জেতা টাকা মামলা করে আদায় চলে না।",
 "Wagering agreements are void.",
 "Wagering agreement void; জেতা অর্থ contract claim হিসেবে recover করা যায় না.",
 "§30", "statute", None),
("c44", "breach-discharge-remedies", "counterintuitive", "spline", "DID YOU KNOW",
 "A serious refusal can end the deal before completion.", "গুরুতর অস্বীকৃতি শেষ হওয়ার আগে চুক্তি শেষ করতে পারে।",
 "One party refuses to perform the promise entirely or disables themselves from performing it. Can the promisee put an end to the contract?",
 "এক পক্ষ পুরো প্রতিশ্রুতি পালন করতে অস্বীকার বা নিজে অক্ষম করল। Promisee কি চুক্তি শেষ করতে পারে?",
 "YES — generally.", "হ্যাঁ — সাধারণত।",
 "Section 39 allows the promisee to end the contract where the other party refuses to perform the promise wholly or disables themselves from performing it, unless the promisee has signified acquiescence in continuing.",
 "ধারা ৩৯: পুরো পালনে অস্বীকার বা অক্ষমতায় promisee চুক্তি শেষ করতে পারে, যদি চালিয়ে যেতে সম্মত না হয়।",
 "Refusal of the whole promise can let the other party end the contract.",
 "পুরো promise perform করতে refusal হলে promisee contract শেষ করতে পারে—যদি continuation-এ acquiesce না করে.",
 "§39", "statute", None),
("c45", "breach-discharge-remedies", "scenario", "lottie", "TRY THIS",
 "Missing a deadline does not always kill the contract.", "সময় মিস মানেই চুক্তি মরা নয়।",
 "A promised date is missed. Does the contract always become voidable?",
 "প্রতিশ্রুত তারিখ মিস। চুক্তি কি সবসময় voidable হয়?",
 "NO — intention matters.", "না — উদ্দেশ্য দেখতে হয়।",
 "Section 55 distinguishes contracts where time was intended to be essential from those where it was not. If time is essential, the unperformed part may become voidable; otherwise compensation for delay may be available.",
 "ধারা ৫৫: সময় অপরিহার্য ছিল কি না। হলে অপূর্ণ অংশ voidable হতে পারে; নাহলে বিলম্বের ক্ষতিপূরণ।",
 "Late performance does not always have the same legal effect.",
 "Deadline miss করলেই সব contract বাতিল হয় না—time essential ছিল কি না দেখতে হবে.",
 "§55", "statute", None),
("c46", "breach-discharge-remedies", "counterintuitive", "image", "DID YOU KNOW",
 "A valid contract can become void later.", "বৈধ চুক্তি পরে void হতে পারে।",
 "After a contract is made, an uncontrollable event makes the promised act impossible or unlawful. What can happen?",
 "চুক্তির পর অনিয়ন্ত্রিত ঘটনায় কাজ অসম্ভব বা অবৈধ হলে কী হয়?",
 "It becomes void then.", "তখনই void হয়।",
 "Section 56 says an agreement to do an act impossible in itself is void. A contract later becomes void when the act becomes impossible or unlawful due to an event the promisor could not prevent.",
 "ধারা ৫৬: নিজেই অসম্ভব কাজ void। পরে অসম্ভব বা অবৈধ হলে সেই সময় থেকে void।",
 "Supervening impossibility or unlawfulness can void a contract.",
 "পরে performance impossible বা unlawful হলে contract সেই সময় থেকে void হতে পারে.",
 "§56", "statute", None),
("c47", "breach-discharge-remedies", "rule_visualizer", "image", "DID YOU KNOW",
 "A new contract can extinguish the old one.", "নতুন চুক্তি পুরনোটিকে নিভিয়ে দিতে পারে।",
 "The parties agree to substitute a new contract, or to rescind or alter the old one. Must the original still be performed?",
 "পক্ষরা নতুন চুক্তি, rescind বা পরিবর্তনে রাজি। পুরনোটা কি এখনও পালন করতে হয়?",
 "NO.", "না।",
 "Section 62 provides that where the parties agree to substitute a new contract, rescind the contract, or alter it, the original contract need not be performed.",
 "ধারা ৬২: novation, rescission বা alteration হলে মূল চুক্তি পালন করতে হয় না।",
 "Novation, rescission or alteration can replace the original duty.",
 "Novation, rescission বা alteration হলে original contract perform করতে নাও হতে পারে.",
 "§62", "statute", None),
("c48", "breach-discharge-remedies", "counterintuitive", "lottie", "DID YOU KNOW",
 "Breach does NOT make you liable for every loss.", "ভঙ্গ মানেই সব ক্ষতির দায় নয়।",
 "A breach indirectly triggers a distant chain of losses nobody contemplated. Are remote and indirect losses automatically compensable?",
 "ভঙ্গ দূরের ক্ষতির শিকল টানল, কেউ ভাবেনি। Remote/indirect loss কি স্বয়ংক্রিয়ভাবে পাওয়া যায়?",
 "NO.", "না।",
 "Section 73 allows compensation for loss that naturally arose in the usual course or that the parties knew, when contracting, was likely from breach. It excludes remote and indirect loss.",
 "ধারা ৭৩: স্বাভাবিক বা চুক্তিকালে জানা সম্ভাব্য ক্ষতি। Remote ও indirect বাদ।",
 "Damages cover natural or contemplated loss, not remote consequences.",
 "Breach-এর natural/known likely loss recoverable হতে পারে; remote indirect loss নয়.",
 "§73", "statute", None),
("c49", "breach-discharge-remedies", "counterintuitive", "spline", "DID YOU KNOW",
 "A written penalty is not automatically what you receive.", "লেখা penalty-ই স্বয়ংক্রিয় প্রাপ্য নয়।",
 "A contract names ৳500,000 payable for breach. Does section 74 automatically award the full ৳500,000?",
 "চুক্তিতে ভঙ্গে ৫,০০,০০০ টাকা। ধারা ৭৪ কি পুরোটাই দেয়?",
 "NO.", "না।",
 "Section 74 allows reasonable compensation when a sum is named or a penalty is stipulated, but compensation cannot exceed the amount named. The written figure is a ceiling, not an automatic award.",
 "ধারা ৭৪: যুক্তিসঙ্গত ক্ষতিপূরণ, নামকরা অঙ্কের বেশি নয়। লেখা অঙ্ক সিলিং, স্বয়ংক্রিয় অ্যাওয়ার্ড নয়।",
 "A named penalty is a cap, not an automatic payout.",
 "Penalty amount পুরোটা automatic নয়; reasonable compensation হবে, named amount-এর বেশি নয়.",
 "§74", "statute", None),
("c50", "breach-discharge-remedies", "scenario", "lottie", "TRY THIS",
 "Cancelling rightly does not erase your loss.", "সঠিকভাবে বাতিল করলেও ক্ষতি মুছে যায় না।",
 "You rightfully rescind a contract because the other side fails to fulfil it. Can you still claim compensation for resulting damage?",
 "অন্য পক্ষ পালন না করায় সঠিকভাবে rescind করলেন। ক্ষতির compensation কি চাইতে পারেন?",
 "YES.", "হ্যাঁ।",
 "Section 75 provides that a person who rightfully rescinds a contract is entitled to compensation for damage sustained through the non-fulfilment of the contract.",
 "ধারা ৭৫: সঠিক rescission-এ অপূর্ণতার ক্ষতির compensation পাওয়া যায়।",
 "Rightful rescission can still lead to compensation.",
 "Rightfully rescind করলেও non-fulfilment-এর damage-এর compensation পাওয়া যেতে পারে.",
 "§75", "statute", None),
]

VIS_TO_ASSET = {"spline": "spline", "lottie": "lottie", "image": "image"}

NANO_BANANA_IDS = {
    "c03", "c04", "c05", "c06", "c09", "c11", "c12", "c14", "c16", "c17",
    "c19", "c20", "c22", "c23", "c24", "c26", "c28", "c29", "c30", "c33",
    "c34", "c36", "c37", "c38", "c39", "c40", "c41", "c43", "c46", "c47",
}


def build() -> dict:
    sections = []
    by_slug = {s["slug"]: {**s, "cards": []} for s in SECTIONS}
    for row in RAW:
        (cid, sec, ctype, vis, label, he, hb, qe, qb, ae, ab, ee, eb, ke, kb, sl, at, note) = row
        card = {
            "id": cid,
            "slug": cid,
            "sort_order": int(cid[1:]),
            "card_type": ctype,
            "label": label,
            "hook_en": he,
            "hook_bn": hb,
            "question_en": qe,
            "question_bn": qb,
            "answer_en": ae,
            "answer_bn": ab,
            "explanation_en": ee,
            "explanation_bn": eb,
            "key_principle_en": ke,
            "key_principle_bn": kb,
            "act_name": "The Contract Act, 1872",
            "section_label": sl,
            "authority_type": at,
            "authority_note": note,
            "asset_type": VIS_TO_ASSET[vis],
            "asset_url": f"/learning/contract-act/{cid}.png" if cid in NANO_BANANA_IDS else None,
            "review_status": "approved",
            "content_version": 1,
        }
        by_slug[sec]["cards"].append(card)
    for s in SECTIONS:
        block = by_slug[s["slug"]]
        sections.append({
            "id": s["slug"],
            "slug": s["slug"],
            "title_en": s["title_en"],
            "title_bn": s["title_bn"],
            "estimated_minutes": s["minutes"],
            "sort_order": s["order"],
            "status": "published",
            "card_count": len(block["cards"]),
            "cards": block["cards"],
        })
    return {
        "subject": {
            "id": "contract-act-1872",
            "slug": "contract-act-1872",
            "title_en": "Contract Act 1872",
            "title_bn": "চুক্তি আইন ১৮৭২",
            "description_en": "Learn one legal idea at a time. First-year contract formation, consent, void agreements and remedies.",
            "description_bn": "একবারে একটি আইনি ধারণা। প্রথম বর্ষের চুক্তি গঠন, সম্মতি, বাতিল চুক্তি ও প্রতিকার।",
            "level_tag": "Year 1",
            "status": "published",
            "coming_soon": [
                {"slug": "constitutional-law", "title_en": "Constitutional Law", "title_bn": "সাংবিধানিক আইন"},
                {"slug": "penal-code", "title_en": "Penal Code", "title_bn": "দণ্ডবিধি"},
                {"slug": "evidence", "title_en": "Evidence", "title_bn": "সাক্ষ্য আইন"},
            ],
        },
        "sections": sections,
    }


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    out = root / "src/v3/learning/contract-act-v1.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    data = build()
    assert sum(len(s["cards"]) for s in data["sections"]) == 50
    out.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
